### ISSUE TITLE
rfx-detector-in : duplicate IDs

### ISSUE THREAD

**Issue by sabamimi** [maxwellhadley/node-red-contrib-rfxcom#106]
Hello Max,
Following your last comment on my previous issue, I used the X10 protocol to retrieve Door/Windows detectors ...but out of my 11 physical sensors some returns the same IDs (the same X10_DOOR/0xXXXX)
I read in a previous issue that you cut down from 6 Exa digit to 4. I wonder if that could be the cause? (just a wild guess on my side)
Meanwhile, as a work around,  I will remove X10 protocol and create a separate rfx-PT2262 device table for those sensors and see if they are unique that way.
Kind regards,
Michel

**Comment by maxwellhadley** [comment]
The reason I changed from 6 hexadecimal digits to 4 is that the X10 security protocol actually allows only 65536 different device addresses (16 bits). The other two digits were automatically generated when a message was _received_ and were always the same. Because I work on the principle that it must be possible to take a message from an `rfx-???-in` node and send it direct to the corresponding `rfx-???-out` node, when I added the X10 security transmit facility, I had to change the address format in this way.

The PT2262-type chips only support a total of 24 message bits. The allocation of these between 'address' and 'data' is completely arbitrary and varies between different systems using the chip & its clones. This isn't enough to provide a unique value for every device & alarm system, so it is highly likely the two sensors are in fact sending the _same_ data. Using the `rfx-PT2262-in` node and disabling X10 reception will show if this is happeneing.

**Comment by sabamimi** [comment]
Thank you for this detail explanation.
I am currently in that process and I will let you know when I have results
It will probably take me few more days to answer since I am travelling today.
Thanks for your support

**Comment by sabamimi** [comment]
Well, I had some time left and I finish the survey.
interestingly they show no duplicates when identified by 
lightning 4 protocol.
BUT
I have decided to not manage those from nodered / Home hassistant and let the Alarm hardware deal with those mainly because of :
- no real need to duplicate the Alarm - Sensors relation in software
- a "range" issue between some sensors and the RFXCOM box

So I will limit the nodered app (for the alarm) to :
- automatically Arm Away when we leave the house

I am using the RFXCOM with other remote controls
We can close the issue unless you want to get to the bottom of the duplicate issue
Kind regards

**Comment by maxwellhadley** [comment]
Since the 'translation' to X10, that seems to be generating these duplicates, is being done by the RFXtrx firmware, it might be worth contacting support@rfxcom.com, or at least letting them know this is happening.
