### ISSUE TITLE
ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by G-Mercier** [maxwellhadley/node-red-contrib-rfxcom#121]
Hi,

I tried to install the contribution on my pc (windows 10) to test RFXcom possibilities with node red.
1/Using powerShell interface I've installed the package using "npm install node-red-contrib-rfxcom".
2/ Reboot NodeRed
3/ Try to find the nodes in the palette, but don't show up.
4/ in Palette Manager, the package is said installed but ERR_DLOPEN_FAILED appears

![image](https://user-images.githubusercontent.com/59644107/147834097-75825436-99d4-431f-aae9-8d484c321e9c.png)

**Comment by maxwellhadley** [comment]
This is a new error to me! Apparently it is something to do with loading a C++ native module directly, used in the internals of `require`. If the load fails the ERR_DLOPEN_FAILED error is raised. I have no idea why it is happening to you.

It might be because of a node.js version mismatch between the version used to compile `serialport` (which the `rfx-port` node uses) and the node version you are running, but that is normally detected when `npm install` runs, and if so, the C++ source is downloaded and recompiled.

Which versions of node.js and node-RED are you using?

**Comment by G-Mercier** [comment]
Hello Max, 
First thanks for your quick response. It might also just be me and my poor skills in node red.
Any way currently my computer runs:

3 Jan 14:46:06 - [info] Node-RED version: v2.1.4
3 Jan 14:46:06 - [info] Node.js  version: v16.13.1
3 Jan 14:46:06 - [info] Windows_NT 10.0.18363 x64 LE

**Comment by G-Mercier** [comment]
Hello Again,

I've tried to uninstall node.js + delete .node-red folder and re-install everything.
Apparently it worked ! Now I can access the rfx nodes.
Regards

G

**Comment by maxwellhadley** [comment]
Glad to hear it is working again. Presumably a file got corrupted, or installed in the wrong place, or something, in the original installation
