### ISSUE TITLE
No connection to RFXtrx433E

### ISSUE THREAD

**Issue by stefanbergh** [maxwellhadley/node-red-contrib-rfxcom#38]
Hello

I'm trying to get this thing working but I can't get it to connect to my RFXtrx433E. 

I set the port to /dev/ttyUSB0 witch work great in Home Assistant with the component https://home-assistant.io/components/rfxtrx/ but here it just say disconnected.

I tried to remove all settings in HA in relation to the RFXtrx component so only Node-red would try to connect to the unit but it did not work either.

I have no clue on how I should move forward, hoping someone could give me a hand in this.

**Comment by maxwellhadley** [comment]
First (obvious) question: have you stopped Home Assistant, so that the RFXtrx433E is available for another program to use?
Second, some Linux systems have a habit of changing the device file path allocated to a USB serial device if the device is unplugged and plugged back in again, so it may not be `/dev/ttyUSB0` any more.
There is a utility script provided with the node to search all available serial ports for RFXCOM devices. From a shell prompt, `cd` to the **node-red-contrib-rfxcom** install directory (the one containing the `package.json` file), and type:

    npm run find-rfxcom

This will print the device port for, and basic information about, all the RFXCOM devices it can find. Note, though, that if some other program has the RFXCOM device open, `find-rfxcom` will not be able to locate it.

**Comment by maxwellhadley** [comment]
The script is installed as a part of node-red-contrib-rfxcom, you should run from the install directory (usually somewhere under `~/.node-red`). It's not part of Home Assistant

**Comment by stefanbergh** [comment]
Hass.io is the OS, based on resinOS and comes preinstalled with Home Assistant. I then installed Node-Red with the add-on from here https://github.com/notoriousbdg/hassio-addons

So I have no access, via ssh, to the install directory of node-red, or at least I have no idea where it is installed.

**Comment by maxwellhadley** [comment]
You mean you installed Node-RED as an add-on to Home Assistant? I suspect you may need to set some permission in a config somewhere to allow it to use the serial port. I'm afraid I can't really help you. Maybe try asking on [https://community.home-assistant.io/t/repository-notoriousbdg-add-ons-node-red-ha-bridge-and-gogs/23247](url).

If you do get it to work please add a comment here and I will add a note to the documentation.

**Comment by maxwellhadley** [comment]
Did you get anywhere?

**Comment by stefanbergh** [comment]
No, I got another RPi with Rasbian and installed it on that one.
