### ISSUE TITLE
Installation issues with Jessie 

### ISSUE THREAD

**Issue by ukmoose** [maxwellhadley/node-red-contrib-rfxcom#4]
Just tried installing on a new install of Jessie on a RPiB

Node-RED version: v0.13.1
Node.js  version: v0.12.6
npm: '2.11.2'

Initially ran into lots of errors complaining about serialport@2.0.6.
To install correctly I needed to use the following command...

sudo npm i --unsafe-perm node-red-contrib-rfxcom

**Comment by maxwellhadley** [comment]
I think this is happening because the version 2.x.x serialport, which is a dependency of node-rfxcom which in turn is a dependency of node-red-contrib-rfxcom, requires compilation. I'll update the README to clarify this.

Testing the migration to serialport 2.x.x is on my list of things to do, which is a very long list unfortunately containing many things other than node-RED hacking! I'm assuming from your comment you did get it to install OK. Please can you test whether 'live' connection and disconnection of the RFXtrx433 works? You should be able to start a flow with or without the RFXtrx433 connected, and it should automatically detect connection & disconnection and update the status flags (after a few seconds), without crashing node-RED. There is one minor niggle: some Ubuntu versions will 'reserve' the /dev/ttyUSBn device file, so that when you reconnect the hardware, it gets a new, different number n. I think (though I haven't tested it) that you can use the corresponding device file in /dev/serial/by-id/ to work around this problem.

I'm in the process of merging my fork of node-rfxcom back into the published npm package, and the serialport 2.x.x issue comes up there too.

**Comment by maxwellhadley** [comment]
Everything should have been OK now on Jessie for quite a while - can I go ahead and close the issue?

**Comment by ukmoose** [comment]
sure

**Comment by maxwellhadley** [comment]
Thanks!
