### ISSUE TITLE
rfxcom is connected to device but not working on node-red

### ISSUE THREAD

**Issue by lpt2007** [maxwellhadley/node-red-contrib-rfxcom#58]
Now I have another problem:

I see my rfxcom but in node red show disconnected. Port is set to /dev/ttyUSB0.

[    2.134489] usb 1-1.5: new full-speed USB device number 4 using dwc_otg
[    2.259199] usb 1-1.5: New USB device found, idVendor=0403, idProduct=6001
[    2.259210] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.259216] usb 1-1.5: Product: RFXtrx433
[    2.259222] usb 1-1.5: Manufacturer: RFXCOM
[    2.259228] usb 1-1.5: SerialNumber: A1XFL0Y9
[    4.431352] usbcore: registered new interface driver brcmfmac
[    5.581569] usbcore: registered new interface driver usbserial
[    5.581670] usbcore: registered new interface driver usbserial_generic
[    5.581755] usbserial: USB Serial support registered for generic
[    5.614937] usbcore: registered new interface driver ftdi_sio
[    5.615046] usbserial: USB Serial support registered for FTDI USB Serial Device
[    5.615331] ftdi_sio 1-1.5:1.0: FTDI USB Serial Device converter detected
[    5.615537] usb 1-1.5: Detected FT232RL
[    5.616439] usb 1-1.5: FTDI USB Serial Device converter now attached to ttyUSB0

**Comment by lpt2007** [comment]
Where [rfxcom] debug messages should apear? Under the debug in top right corner?

If this is the right place, there is nothing.

**Comment by maxwellhadley** [comment]
If you start Node-RED from the command line, debug messages and other console output will appear on the terminal window. If it is started as a daemon or service of some sort, they will go to a log file somewhere. Exactly where depends on which mechanism the OS is using. The messages don't appear on the debug panel, because they come from the node-rfxcom package which does not know anything about Node-RED.

I have never used Docker, so I don't know where these messages might be ending up - possibly /var/log, or /usr/share/logs or somewhere like that, but that is just a guess. Try asking on the Node-RED forum, as it's more of a general question. [https://discourse.nodered.org](url)

**Comment by lpt2007** [comment]
I slove the problem.

Solution is there:
[https://github.com/hassio-addons/addon-node-red/issues/10](url)

Thanks a lot for your help.

**Comment by maxwellhadley** [comment]
Glad you got it working!
