### ISSUE TITLE
Add cartelectonic /TIC

### ISSUE THREAD

**Issue by ouv27** [maxwellhadley/node-red-contrib-rfxcom#59]
Hi,

Is it possible to add new device like cartelectonic /TIC :
Packettype    = Cartelectronic
subtype       = TIC

Tks for your work.

Bye

**Comment by maxwellhadley** [comment]
@ouv27 I am currently looking at this issue (adding the Cartelectronic Linky meter module). Please could you help explain about the data the packet provides:

- What does 'contract type/current price time' mean? How best should I encode this in the message payload?
- Are the counter units watt-hours?
- If the TeleInfo is not present, does this mean that any/all of the other data is invalid, or is this just related to sending the energy usage data to the electricity supplier?
- What do the tariff colours mean?
- What is PEJP? And what is the significance of 'demain'? Does this mean the tariff information does not apply until the next day? If so, what is the colour in use today?
- What does 'no change price time warning' mean?

> state:
Bit 0 not used
Bit 1 PAPP (Apparent power) Valid: 1=valid
Bit 2 TeleInfo Not present: 1=not present
Bit 3-4 PEJP or DEMAIN:
 00 = no change price time warning
 01 = white
 10 = blue
 11 = red/PEJP

I see the new Linky device always has a tariff colour for both today & tomorrow, and doesn't have PEJP

Finally, should I use French names for the payload properties, since this is a packet type that is only used in France? (If so, help with translation would be welcome!)

**Comment by maxwellhadley** [comment]
Now supports Cartelectronc TIC & Linky meters. All available data is provided
