### ISSUE TITLE
Somfy Node-red

### ISSUE THREAD

**Issue by ocverclock** [maxwellhadley/node-red-contrib-rfxcom#71]
hi,
how to send the order with the node rfx-blind to somfy.
in the RFXmngr, it's okay for the control, but in node-red i don't stand how send the order.
in node Inject , payload string up and in topic 04050401 (in the RFXmngr it's Id 4 05 04 and unit 1).
Please can you say me.

**Comment by maxwellhadley** [comment]
Hi,

If you are using 'normal' Somfy blinds, I think your message should have a topic of:

    RFY/0x040504/1

and a payload of:

    Up

The first part of the topic is the 'Type' as shown in rfxmngr, the second part is the 'Id' as a single hexadecimal number, and the third part is the 'Unit Code'. However, if you are using GEOM blinds, the topic needs to be:

    RFY_RESERVED/0x040504/1

(This is because RFXCOM have changed the name of this subtype recently)

I hope this gets you going!

**Comment by ocverclock** [comment]
You are the best

**Comment by maxwellhadley** [comment]
I assume it worked then? :)
